appuniversum/ember-appuniversum

addon/components/au-date-picker.hbs
addon/components/au-date-picker.js
app/components/au-date-picker.js
ember-cli-build.js
package-lock.json
package.json
tests/dummy/app/components/sidebar.hbs
tests/dummy/app/router.js
tests/dummy/app/styles/_shame.scss
tests/dummy/app/templates/docs/components/au-date-picker-demo/adapter-default.js
tests/dummy/app/templates/docs/components/au-date-picker-demo/localization-default.js
tests/dummy/app/templates/docs/components/au-date-picker-demo/template.hbs
tests/dummy/app/templates/docs/components/au-date-picker.md
tests/integration/components/au-date-picker-test.js

DONE:
- Transformed Duetds date-picker into an ember-component 
- Filled out documentation with demo's and arguments
- Added error handling
- Modified the default values slightly
NOTES:
- Tested it 
- Should not interfere with existing code
TO-DO:
- Styling is default. Changes will probably need to be made, an example is when passing in the attribute disabled=true, there is no visual feedback to the date picker being disabled.
- Maybe change default formatting to something more suitable
ref: https://github.com/duetds/date-picker

Add date-picker component (Duetds)

---

addon/components/au-link.hbs

#54 actually breaks the component when no `@model` attribute is needed. This PR hopes to fix that.
The problem is that LinkTo treats a `@model` argument with the values `undefined` or `null` as invalid. 
When no model is needed for the route, the `@model` argument to LinkTo has to be entirely absent. 
This solution makes the behavoir of AuLink deviate from the behavior of LinkTo when the model is null or undefined. In partircular
- route doesnt need model, `@model` argument is provided but is falsey:
AuLink: works fine
LinkTo: link doesnt work and prints a warning to console when clicked
- route needs model, `@model` argument is provided but falsey:
**AuLink: link doesnt work, no warning or error** -> this could be problematic (this is the same behavior as forgetting to give the `@model` …

Make component work again when no model is needed

---

package-lock.json
package.json

Ember Wormhole is no longer used so it can safely be removed.

chore: remove the ember-wormhole dependency

---

addon/components/au-link.hbs

The `{{with}}` helper will be deprecated in the near future.
https://emberjs.github.io/rfcs/0445-deprecate-with.html

Use `{{let}}` instead of `{{with}}`

---

app/serializers/application.js

This was exported from the app folder by accident and it should actually be added to the dummy app instead.
Since the serializer is no longer used, it can be removed instead.
This will affect projects that don't have an application serializer themselves and unknowingly depend on the one from this addon. So this will require a minor version bump (ember-appuniversum is still in the 0.X version range). 
For reference [frontend-toezicht-abb](https://github.com/lblod/frontend-toezicht-abb) is the only project that seems to rely on this behavior.

[Breaking change] Remove the application serializer

---

package-lock.json
package.json
tests/dummy/app/templates/docs/patterns/au-content-header.md

Gh pages deploys the docs website on the `ember-appuniversum` path. This has the side effect that absolute urls to images don't work properly. prefixing them with the rootUrl fixes the problem.
Closes #64

Use the root-url helper to wrap all image paths

---

package-lock.json
package.json
tests/dummy/app/templates/docs/outline/getting-started.md

`ember-cli-autoprefixer` is installed as a dependency which means all consuming projects will install it as well.
I think a better solution would be to leave this choice to the end user since they can run autoprefixer in a different way as well. This is especially relevant when the consuming project sets up a PostCSS build pipeline (to make use of PurgeCSS for example) since autoprefixer can run as a PostCSS plugin as well.
This is a breaking change so it will require another minor version bump.

Remove autoprefixer dependency

---

addon/components/au-control-checkbox.hbs
addon/components/au-control-checkbox.js
tests/dummy/app/templates/docs/atoms/au-form-checkbox.md

- Fixed passing the checked-state
- OnChange now passes the checked state & event context
- added onChange to the docs 
Tested it with multiple checkboxes and changing checked state dynamically

Improve checkbox handling

---

addon/components/au-modal.hbs
addon/components/au-modal.js
tests/integration/components/au-modal-test.js

If a modal was closed by pressing one of the close buttons, `@closeModal` would be called twice. This can have some side effects in apps that don't expect that behavior. The old behavior can be verified by commenting out the `if` check, and running the tests.

Prevent the closeModal callback from running twice

---

package-lock.json
package.json
tests/dummy/app/templates/docs/atoms/ember-power-select.md

This addon only provides styles so the dependency isn't needed. Consuming projects can choose if they want to use ember-power-select by installing the addon and importing the styles.
Closes #92

Make ember-power-select an optional dependency

---

package.json

No need to use my fork anymore

Deprecation warning fixed in v2.0.1 release

---

addon/components/au-time-picker.js

While building the app, YUIDoc was throwing "Missing item type" errors due to some multi line comments not having any types. This adds some basic types to remove those warnings.

Silence the YUIDoc build warnings

---

addon/components/au-time-picker.js

These generate menu items that are not needed. This also changes the comments to a single asterisk version to prevent YUIDoc from throwing build warnings.
Sorry about that :smile:.
Closes #100

Remove the YUIDoc comment annotations

---

addon/components/au-modal.js
tests/integration/components/au-modal-test.js

The [previous fix](https://github.com/appuniversum/ember-appuniversum/pull/94) didn't cover the case where the modal was conditionally rendered (and you set `@modalOpen` to always be `true`). In that case if you completely destroy the modal component, the `@closeModal` action is still getting called twice. 
As I explained [here](https://github.com/josemarluedke/ember-focus-trap/issues/36#issuecomment-850844483) I think the root of this issue is that we are misusing the `onDeactivate` event while we are not interested in the "deactivate" part at all. We only want to know if the user wants to close the modal by pressing escape (or clicking outside of it). `onDeactivate` is the only option though since focus-trap doesn't have dedicated events for that …

Prevent that the @closeModal action is run more than once

---

addon/components/au-link.hbs
addon/components/au-link.js
tests/dummy/app/templates/docs/atoms/au-link.md

This makes it possible to style links as buttons by using the `button` or `button-secondary` skins. Let me know if I need to use different skin names.
Closes #110

Add new button skins to the `<AuLink>` component

---

addon/components/au-link.hbs
addon/components/au-navigation-link.hbs
tests/dummy/app/templates/docs/atoms/au-link.md
tests/dummy/app/templates/docs/atoms/au-navigation-link.md

This can be used to provide query parameters to the route.
Closes #88

Add a `@query` argument to the link components

---

addon/components/au-link.hbs
addon/components/au-link.js
addon/components/au-main-header.hbs
addon/components/au-navigation-link.hbs
addon/components/au-navigation-link.js
tests/dummy/app/components/sidebar.hbs
tests/dummy/app/templates/docs/atoms/au-badge.md
tests/dummy/app/templates/docs/atoms/au-button.md
tests/dummy/app/templates/docs/atoms/au-form-input.md
tests/dummy/app/templates/docs/atoms/au-link.md
tests/dummy/app/templates/docs/atoms/au-navigation-link.md
tests/dummy/app/templates/docs/atoms/au-pill.md
tests/dummy/app/templates/docs/components/au-accordion.md
tests/dummy/app/templates/docs/components/au-alert.md
tests/dummy/app/templates/docs/components/au-card.md
tests/dummy/app/templates/docs/outline/webuniversum.md
tests/dummy/app/templates/docs/patterns/au-card-edit.md
tests/dummy/app/templates/docs/patterns/au-main-footer.md
tests/dummy/app/templates/docs/patterns/au-toolbar.md

[As mentioned before](https://github.com/appuniversum/ember-appuniversum/issues/88#issuecomment-844026558) I think `@route` is a better and more intuitive name for that argument since that's what `<LinkTo>` uses.
Not a breaking change since `@linkRoute` still works (but it will show a deprecation).

Deprecate the @linkRoute argument for the link components

---

addon/components/au-data-table/number-pagination.hbs
addon/components/au-data-table/number-pagination.js
tests/dummy/app/templates/docs/components/au-data-table.md

This shows the total number of visible rows when the pagination meta object doesn't include a count. This means that arrays that are created client side are supported as well.
Closes #136

Add a total row fallback to the data table component

---

addon/components/au-time-picker.hbs
addon/components/au-time-picker.js
addon/helpers/format-time-digit.js
app/helpers/format-time-digit.js
app/helpers/format-time.js
tests/dummy/app/templates/docs/atoms/au-form-datepicker-demo/on-change.js
tests/dummy/app/templates/docs/atoms/au-form-timepicker.md
tests/integration/helpers/format-time-test.js

This PR includes the following adjustments:
- Added `showSeconds` argument: hides/shows the seconds input
- Added `showNow` argument: hides/shows the now button
- Upgraded the component to Octane
- Corrected the min/max values of hours, minutes & seconds
- Renamed the `format-time` helper to avoid conflicts with other libraries/plugins (for example `ember-intl`)
- Adjusted component documentation
Feedback is more then welcome!

Timepicker improvements (added arguments, octane upgrade & minor tweaks)

---

.github/workflows/ci.yml

This change ensures that workflows are canceled when new changes come in which means resources aren't wasted on outdated workflows.
More information: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency

Cancel workflows when they become outdated

---

addon/components/au-modal-body.hbs
addon/components/au-modal-footer.hbs
addon/components/au-modal.hbs
stories/4-components/Content/AuModal.stories.js
tests/integration/components/au-modal-test.js

This modernizes the component by adding `title`, `body` and `footer` named blocks. The non-block version is still fully supported to keep the change backwards compatible.
New usage:
```hbs
<AuModal @modalOpen={{true}}>
<:title>Some title</:title>
<:body>Body</:body>
<:footer>Footer</:footer>
</AuModal>
```
We could also add deprecations to guide users to the newer version?

Add named block support to the `AuModal` component

---

addon/components/au-accordion.js
addon/components/au-brand.js
addon/components/au-dropdown.js
addon/components/au-link.js
addon/components/au-modal.js
addon/components/au-navigation-link.js

We didn't remove the deprecated code in the 1.0 release, so we'll do it in v2.

Update the deprecation versions

---

addon/components/au-input.hbs
addon/components/au-input.js
stories/4-components/Forms/AuInput.stories.js
tests/integration/components/au-input-test.js

Ember's Input component requires that the type is passed as an argument instead of an attribute. [This has always been documented like this](https://api.emberjs.com/ember/release/classes/Ember.Templates.components/methods/Input#input-html-attributes-to-avoid) but somewhere between 3.24 and 3.28 it stopped supporting the attribute version.
Closes #217

Add a `@type` argument to the AuInput component

---

addon/components/au-alert.hbs
addon/components/au-alert.js
stories/4-components/Notifications/AuAlert.stories.js
tests/integration/components/au-alert-test.js

This deprecates the `alert` prefixed argument names for the `AuAlert` component.
I also added some tests since it didn't have any yet.
Closes #236

Deprecate the `alert` prefixed argument names of the `AuAlert` component

---

addon/components/au-time-picker.hbs
addon/components/au-time-picker.js

- make sure the values are shown in Ember 3.27+
- only call `@onChange` if it's a function (this was throwing errors in Storybook)
- ensure integer values are returned instead of strings
This fixes the [Storybook example](https://appuniversum.github.io/ember-appuniversum/?path=/story/components-forms-autimepicker--component) and was causing issues in one of the LBLOD projects.

`AuTimepicker` fixes

---

package-lock.json
package.json

Consuming apps need to install this dependency as well. It's breaking apps that do not have tracked-toolbox installed already.
Follow-up of #252, I missed this during the code review 😅.

Move tracked-toolbox to the dependencies list

---

addon/components/au-accordion.hbs
addon/components/au-toolbar-group.js
addon/components/au-toolbar.hbs
stories/4-components/Content/AuCard.stories.js
stories/4-components/Layout/AuToolbar.stories.js
stories/4-components/Tables/AuDataTable.stories.js
stories/6-templates/AppBreadcrumbs.stories.js
stories/6-templates/AppEditor.stories.js
tests/helpers/deprecations.js
tests/integration/components/au-alert-test.js
tests/integration/components/au-toolbar-group-test.js
tests/integration/components/au-toolbar-test.js

This yields the `AuToolbarGroup` component from the `AuToolbar` component and deprecates directly invoking it.
Not a breaking change, but it will create _a lot_ of noise since the component is used quite a bit 😄.
Closes #251

yield the `AuToolbarGroup` component from the `AuToolbar` component

---

addon/components/au-date-picker.hbs
addon/modifiers/au-props.js
app/modifiers/au-props.js
package.json
tests/integration/modifiers/au-props-test.js

The ember-prop-modifier addon is no longer maintained so we replace it with a custom modifier for now.
This solves some of the issues in #223

Replace `{{prop}}` with a custom modifier

---

addon/components/au-file-card.hbs
addon/components/au-time-picker.hbs
app/styles/ember-appuniversum/_c-alert.scss
app/styles/ember-appuniversum/_c-button.scss
app/styles/ember-appuniversum/_c-dropdown.scss
app/styles/ember-appuniversum/_c-file-card.scss
app/styles/ember-appuniversum/_c-file-upload.scss
app/styles/ember-appuniversum/_c-modal.scss
app/styles/ember-appuniversum/_c-pill.scss
app/styles/ember-appuniversum/_c-timepicker.scss

For consistency reasons and clarity (after a long discussions and research into current conventions) it was decided to add a hand cursor to all actions (buttons, dropdowns, ...). Some users also reported buttons with a default cursor as a bug.
Additional fix: add component namespace to file card classnames

Use hand cursor for actions

---

addon/components/au-modal.hbs
addon/components/au-modal.js
tests/integration/components/au-modal-test.js

- remove the hack that was needed to prevent the double "closeModal" call (fixes #129)
- more tests

AuModal improvements

---

addon/components/au-modal.hbs
addon/components/au-modal.js
tests/integration/components/au-modal-test.js

The previous refactor didn't take into account that embedded components could also be rendered in external elements. Since focus-trap considers these "outside" elements, the modal was closed when clicking on them.
Fixes #282

Fix a problem where selecting a PowerSelect option closes the modal

---

stories/5-components/Brand/AuContentHeader.stories.js
stories/5-components/Buttons/AuButton.stories.js
stories/5-components/Content/AuHeading.stories.js
stories/5-components/Content/AuModal.stories.js
stories/5-components/Forms/AuHelptext.stories.js
stories/5-components/Forms/AuLabel.stories.js
stories/5-components/Links/AuLink.stories.js
stories/5-components/Links/AuLinkExternal.stories.js
stories/5-components/Navigation/AuNavigationLink.stories.js
stories/5-components/Notifications/AuPill.stories.js
stories/7-templates/AppLogin.stories.js

Some stories where depending on the "implicit fallback" behavior to work, which is removed in Ember 4.

Make the Stories compatible with Ember 4

---

addon/components/au-file-upload.hbs

While working on #302 I noticed that we were still using the old argument names which means we would trigger deprecations that consuming applications can't fix themselves 😄.
It seems we missed these during the implementation of the deprecations (#237).

Fix `AuAlert` deprecations in the `AuFileUpload` component

---

package-lock.json
package.json

ember-power-select v6 was recently released without any breaking API changes so we can safely allow that version as well.
This will allow consuming apps to update to ember-power-select v6 as well.

Add support for ember-power-select v6

---

.github/workflows/ci.yml
README.md
package.json

Node 12 has been EOL since 30/4/2022.
Closes #256

Drop node 12 support

---

addon/components/au-button.hbs
addon/components/au-button.js
app/styles/ember-appuniversum/_c-button.scss
app/styles/ember-appuniversum/_c-icon.scss
app/styles/ember-appuniversum/_s-root.scss
stories/7-templates/AppLogin.stories.js
tests/integration/components/au-button-test.js

The following changes should allow easier integration of button component within the Kaleidos (or any) app:
- Switch regarding spacing (inside button) from margins to gap: enables automatic spacing of children + fixes icon-only redundant spacing issue.
- Add `au-c-button--icon-only` class if an icon is defined and @hideText is set to true: allows for additional styling if needed (not applied by default). As used within the link component. E.g. inside the Kaleidos app, we need less horizontal padding on icon-only buttons.
Also added testing to cover the changes mentioned above.

Various small improvements to button component

---

addon/components/au-file-upload.hbs
addon/components/au-file-upload.js
package-lock.json
package.json
stories/5-components/Forms/AuFileUpload.stories.js
tests/unit/utils/is-valid-file-type-test.js

This bumps ember-file-upload to v7 which required some code changes.
It's also a breaking change since it requires Ember 3.25+ so we need to release it as part of the v2 release.
~~The major change for consuming projects is that ember-file-upload [removed all validations](https://github.com/adopted-ember-addons/ember-file-upload/pull/578) and pushed that responsibility back to the consumers. At the moment I expose the `@filter` argument for this, so projects can decide if they want stricter validations, but we can also try to mimic the setup that ember-file-upload v4 used.~~ 
We reimplemented the ember-file-upload v4 validations so in theory the public API of the `AuFileUpload` component wasn't changed with this PR.
Closes #222

ember-file-upload v5+ update

---

addon/components/au-file-card.hbs
addon/components/au-link-external.hbs
addon/components/au-link-external.js
addon/components/au-link.hbs
addon/components/au-link.js
addon/components/au-main-header.hbs
app/styles/ember-appuniversum/_c-link.scss
stories/5-components/Links/AuLink.stories.js
stories/7-templates/AppBreadcrumbs.stories.js
stories/7-templates/AppEditor.stories.js

The changes within https://github.com/appuniversum/ember-appuniversum/pull/313 caused an unintended issue: when the AuLink component is displayed with either a `button`, `button-secondary` or `button-naked` skin there is additional whitespace between the icon and the text.
Preview URL: https://appuniversum.github.io/ember-appuniversum/?path=/story/components-links-aulink--component&args=skin:button
This issue was not directly caught because the AuLink component with a button-like skin is currently not covered by the Chromatic tests.
The changes I made:
- Performed the same structural (& functional) changes on AuLink and AuLinkExternal made within the AuButton component (see: https://github.com/appuniversum/ember-appuniversum/pull/313/files#diff-08dd95d3f03a9928ab26dce9607419e9c22e141e50a28 …

Spacing issue (icon + text) link component with button skin

---

addon/components/au-dropdown.hbs
addon/components/au-dropdown.js
tests/integration/components/au-dropdown-test.js

This removes the duplicated AuButton. We now use focus-trap's clickOutsideDeactivates event to detect when an outside click happened, and only call the close method if the target element is not the toggle button. This prevents the dropdown from instantly reopening again. The previous implementation worked around this by rerendering a different button component which meant the click event was ignored.

AuDropdown refactoring

---

addon/components/au-button.hbs
addon/components/au-button.js
addon/components/au-link.hbs
addon/components/au-link.js
app/styles/ember-appuniversum/_c-button.scss

The following class-related issues persist within the `AuButton` & `AuLink` component.
`AuButton`
- When defining an icon & enabling the `hideText` property on a button with a `link` or `link-secondary` skin, the button lacks the correct styling (see screenshot below).
- When setting the size property to `large` on a button with a `link` or `link-secondary` skin (which should not be a possibility at the moment), the component gets a unnecessary `au-c-button--large` class that could cause unintended styling issues in the future.
`AuLink`
- When defining an icon & enabling the `hideText` property on a link with a `button`, `button-secondary` or `button-naked` skin, the link lacks the correct icon-only class (see screenshot below).
- When the component checks internally what specific …

Various class issues within button & link component

---

package-lock.json
package.json

This resolves the ember-modifier deprecation messages.
Closes #223

Update ember-inputmask5 to v4

---

app/styles/ember-appuniversum/_c-control.scss

The following small change should allow easier integration of control components within the Kaleidos (or any) app:
- Switch regarding spacing (inside control components like checkbox & radio) from margins to gap: enables automatic spacing of children.

Small spacing improvement to control components

---

addon/components/au-link-external.hbs
addon/components/au-link-external.js
app/styles/ember-appuniversum/_c-link.scss
stories/5-components/Links/AuLinkExternal.stories.js

The addition of 3 (missing) `button-` skins (`button`, `button-secondary` & `button-naked`) to the `AuLinkExternal` component.
See https://github.com/appuniversum/ember-appuniversum/issues/339 for additional information.

Addition of button skins for external link component

---

.github/workflows/publish.yml
package.json

Publishing from CI has the advantage that everyone with write permissions to the repo can release a new version without having to have npm rights to the package.
Closes #219

Use Github Actions to publish to npm

---

app/styles/ember-appuniversum/_s-colors.scss
package-lock.json
package.json

as per https://sass-lang.com/documentation/breaking-changes/function-units#weight the color.mix function now needs an explicit unit for the third argument.
This commit applies the suggested fix

Provide explicit unit to `mix` builtin

---

addon/components/au-control-checkbox.hbs
tests/integration/components/au-control-checkbox-test.js

The addition of support for block content within the `au-control-checkbox` component.
The reason for this is mostly cases like this within Kaleidos:

Addition of support for block content within checkbox component

---

addon/components/au-control-checkbox.hbs
app/styles/ember-appuniversum/_c-control.scss
stories/5-components/Forms/AuCheckbox.stories.js

Addition of a visual indeterminate state for the `AuControlCheckbox` component.
See https://github.com/appuniversum/ember-appuniversum/issues/335 for additional information.
Closes #335

Addition of indeterminate state for the checkbox component

---

addon/components/au-control-checkbox.hbs
addon/components/au-control-checkbox.js
addon/components/au-control-radio.hbs
addon/components/au-control-radio.js
app/styles/ember-appuniversum/_c-control.scss

When implementing the `AucontrolCheckbox` component within Kaleidos I encountered the following alignment issue:
It seems like solo (without a label) control components (like `AucontrolCheckbox` & `AucontrolRadio`) are not aligned properly.
The adjustments in this PR fixes this issue for both `AucontrolCheckbox` & `AucontrolRadio`:
(the label-less version of both control components can be viewed inside the table I temporarily added locally)

Improvement of solo (label-less) control (checkbox & radio) components

---

tests/helpers/deprecations.js
tests/integration/components/au-date-picker-test.js

This util causes tests to fail if other code unrelated to the code being tested also triggers a deprecation. The better solution is to use the `hasDeprecation` or `hasDeprecationStartingWith` utils and expect them to be false.
This should fix the failing ember-canary scenario.

Replace the `hasNoDeprecations` test util

---

stories/5-components/Forms/AuFieldset.stories.js
stories/5-components/Forms/AuRadio.stories.js
stories/6-patterns/forms.stories.js

Found a bug that the AuRadioButton pass down `checked` instead of `@checked` so I fixed the docs.

Au radio control checked should be without the @

---

addon/components/au-link.hbs
addon/components/au-link.js
addon/components/au-navigation-link.hbs
addon/components/au-navigation-link.js
addon/components/au-pill.hbs
addon/components/au-pill.js
addon/private/helpers/link-to-models.js
app/helpers/au-link-to-models.js
tests/unit/helpers/au-link-to-models-test.js

By moving it into a private folder and removing the app re-export, it is very clear that this helper shouldn't be used outside of this addon itself.

Make the au-link-to-models helper truly private

---

.storybook/preview-body.html
addon/components/au-modal-container.hbs
addon/components/au-modal.js
app/components/au-modal-container.js
ember-cli-build.js
index.js
stories/5-components/Content/AuModal.stories.js
tests/integration/components/au-modal-container-test.js
tests/integration/components/au-modal-test.js

This deprecates the element that is added to the index.html file during the build. Users can now use the `AuModalContainer` component instead. (The `app/templates/routes/application.hbs` is a good place to put it).
To hide the deprecation warning a build-time flag can be added to the app's ember-cli-build.js file:
```js
'@appuniversum/ember-appuniversum': {
disableWormholeElement: true,
},
```
Closes #258

Deprecate the `#ember-appuniversum-wormhole` element

---

stories/5-components/Forms/AuCheckbox.stories.js
stories/5-components/Forms/AuRadio.stories.js

Closes #365 
I didn't rename the files themselves since I plan on renaming the components anyways.

Use the proper name for the checkbox and radio components in the documentation

---

addon/components/au-date-input.hbs
addon/components/au-date-input.js
addon/components/au-date-picker.js
addon/utils/date.js
app/components/au-date-input.js
app/styles/ember-appuniversum/_c-input.scss
package-lock.json
package.json
stories/5-components/Forms/AuDateInput.stories.js
tests/integration/components/au-date-input-test.js

This adds a new `<AuDateInput>` component that should be a drop-in replacement for the `<AuDatePicker>` component.
https://user-images.githubusercontent.com/3533236/216779830-60c6520e-d0f4-444d-b4c1-c816524ed4b1.mov
Closes #119

Add a `<AuDateInput>` component

---

addon/components/au-input.hbs
addon/components/au-input.js
package-lock.json
package.json
stories/5-components/Forms/AuInput.stories.js

This allows users to pass options directly into the `Inputmask` instance so it's now a lot more flexible.
At its most basic form, `@maskOptions` can be used as a replacement of `@mask` and `@maskPlaceholder`:
```diff
<AuInput
-  @mask="99.99.99-999.99"
-  @maskPlaceholder="_"
+  @maskOptions={{hash
+    mask="99.99.99-999.99"
+    placeholder="_"
+  }}
@onChange={{this.setRijksregisternummer}}
/>
```
But it allows users to pass any of the [inputmask options](https://github.com/RobinHerbots/Inputmask#options). This opens up the use of aliases, or any of the event callbacks to have more finegrained control.
Closes #207

Add a `@maskOptions` argument to the AuInput component 

---

addon/components/au-control-radio.hbs
stories/5-components/Forms/AuFieldset.stories.js
stories/5-components/Forms/AuRadio.stories.js
stories/6-patterns/forms.stories.js

A rework of the `AuControlRadio` component:
~~- [ ] Creation of new `AuCheckbox` & `AuRadio` component with the addition of a deprecation warning for the 'legacy' version of those components (see comment https://github.com/appuniversum/ember-appuniversum/issues/365#issuecomment-1418722020 by @Windvis).~~ Will be done in a future PR.
If needed, additional work items can be added to this PR.

Improve the consistency between the AuControlCheckbox and AuControlRadio components

---

index.js

This fixes the problem where an exception is thrown if no config is provided to the addon.

Fix the disableWormholeElement exception

---

addon/components/au-button.hbs
addon/components/au-button.js
tests/integration/components/au-button-test.js

Users shouldn't be able to click buttons that are in the loading state since an action is already running.

Disable the `AuButton` component when it is in the loading state

---

addon/components/au-main-header.js

This fixes an issue where the AuMainHeader component would trigger a type error exception if the `#main` element didn't exist.
Closes #376

Only call `.focus` if the element exist

---

app/styles/ember-appuniversum/_c-toggle-switch.scss

This change prevents the visual switch from shrinking below its minimum width.
Before:
After:
Supersedes #377

Fix a `<AuToggleSwitch>` shrinking issue

---

addon/components/au-toggle-switch.hbs
addon/components/au-toggle-switch.js
app/styles/ember-appuniversum/_c-toggle-switch.scss
stories/5-components/Forms/AuToggleSwitch.stories.js
tests/integration/components/au-toggle-switch-test.js

Addition of the following functionality for the `AuToggleSwitch` component:
- The correct visualisation of the component if there is no label defined (this issue has already been fixed for `AuControlCheckbox` and `AuControlRadio`).
- The possibility of defining a certain alignment for the label (E.g. showing the label on the left of the actual toggle-switch).
- The possibility of passing content to the component as block (E.g. adding a loader to the toggle-switch) along with the existing `@label` method.
Together with some general adjustments:
-  Quick refactor from margin-based spacing to `gap` (already made within a few other components).
See https://github.com/appuniversum/ember-appuniversum/issues/385 for additional information.

Addition of various functionality for the toggle-switch component

---

addon/components/au-modal.hbs
addon/components/au-modal.js
app/styles/ember-appuniversum/_p-ember-power-select.scss
package-lock.json
package.json

This PR continues the works already done within https://github.com/appuniversum/ember-appuniversum/pull/391 but without the patching of the `ember-focus-trap` package:
- Update of the `ember-focus-trap` package (new release contains https://github.com/josemarluedke/ember-focus-trap/issues/71).
- Addition of `additionalElements` argument (with `#ember-basic-dropdown-wormhole` as a default) to the `AuModal` component to enable focus/tabbing within `ember-power-select` instances when following variables are met:
- The `AuModal` instance has `@overflow` disabled.
- The `ember-focus-trap` instance has `@renderInPlace` disabled.

Update of ember-focus-trap package and application of additional elements argument to modal component

---

index.js

This ensures that the message is hidden when addons also list Appuniversum as a dependency. In general this isn't recommended and a peerDep would be better suited, but it happens and it would always display the deprecation warning even if the project already included the config.
The reason for this is that the `included` hook would also run in the context of the addon which wouldn't have the flag set.

Only show the wormhole deprecation in apps

---

addon/components/au-accordion.hbs
addon/components/au-brand.hbs
addon/components/au-card.hbs
addon/components/au-content-header.hbs
addon/components/au-icon.hbs
app/styles/ember-appuniversum/_p-ember-power-select.scss
stories/5-components/Forms/PowerSelect/SingleSelect.stories.js
tests/dummy/app/components/au-icon-list.hbs

- fix aria hidden toggle on icons: did not work as intended
- remove duplicate banner role on content header: causes a landmark conflict with the <header>
- add aria-labelledby on the brandlink: link appears empty on some accessibility tests
- fix ember power select placeholder color contrast
- improve accordion accessibility: removed aria-hidden, hide the toggle icons (see icons aria-hidden fix).

Accessibility fixes

---

package-lock.json
package.json

This should allow projects to update to v7 without having to use overrides to force a single version.

Allow ember-power-select v7

---

addon/components/au-modal.hbs

It seems like the `allowOutsideClick` argument was wrongly removed (my bad!) within https://github.com/appuniversum/ember-appuniversum/pull/412 as it creates clicking issues within set-ups where elements/components are displayed through a wormhole within the modal component.

Clicking issue for wormhole elements/components within the modal component

---

package.json

We were already testing against Ember v5, so this simply allows new projects to use Appuniversum without needing overrides.

Add Ember v5 support

---

addon/components/au-accordion.hbs
addon/components/au-button.js
addon/components/au-card.hbs
addon/components/au-data-table/number-pagination.hbs
stories/5-components/Brand/AuMainHeader.stories.js
stories/5-components/Content/AuCard.stories.js
stories/5-components/Navigation/AuDropdown.stories.js
stories/5-components/Tables/AuDataTable.stories.js
stories/6-patterns/forms.stories.js
stories/7-templates/AppBreadcrumbs.stories.js
stories/7-templates/AppEditor.stories.js
stories/7-templates/AppSidebar.stories.js
tests/integration/components/au-button-test.js

It seems this was marked as deprecated in the code, but a deprecation message was never added. This adds that so we can remove it in v3.
This is an alias for the `link` skin so it can simply be renamed.

Deprecate the `tertiary` button skin

---

addon/components/au-toggle-switch.js
stories/5-components/Forms/AuToggleSwitch.stories.js
tests/integration/components/au-toggle-switch-test.js

We already supported an `@onChange` handler so the 2-way-binding isn't needed anymore.

Deprecate the 2-way-binding setup in the AuToggleSwitch component

---

addon/components/au-date-input.hbs
addon/modifiers/au-date-input.js
app/modifiers/au-date-input.js
stories/5-components/Forms/AuDateInput.stories.js
tests/integration/modifiers/au-date-input-test.js

This allows projects to style their own input in case the `AuDateInput` component isn't flexible enough.
Closes #392

Add a `{{au-date-input}}` modifier

---

addon/components/au-textarea.hbs
addon/components/au-textarea.js
stories/5-components/Forms/AuTextarea.stories.js
tests/integration/components/au-textarea-test.js

This removes the 2-way-binding setup in the `AuTextarea` component.
Simply replace the `@value` argument with a value property and event handler that updates the value instead.
```diff
- <AuTextarea @value={{this.someValue}} />
+ <AuTextarea value={{this.someValue}} {{on "change" this.handleChange}} />
```
Closes #436

Deprecate the `AuTextarea` `@value` argument

---

addon/components/au-loader.gjs
tests/integration/components/au-loader-test.js

We added a deprecation comment to the component without actually triggering a deprecation. I stumbled uppon this by accident when removing the other deprecations 😄. It would be nice if we could also remove this in v3.

Deprecate the `@size` argument for the `AuLoader` component

---

.github/workflows/ci.yml
README.md
package.json
tests/dummy/config/ember-try.js

Both are end-of-life. 4.8 still receives security patches until december.
https://emberjs.com/releases/lts/

Drop Ember 3.28 and 4.4 support

---

styles/utilities/_u-flex.scss

These were accidentally using the breakpoints as the upper bound instead of lower bound. 
This deprecates the old behavior and adds a global variable that can be set to enable the min-width based queries.
Closes #394

Fix the responsive flex utilities

---

addon/components/au-button.gts
addon/components/au-loader.gts
addon/private/components/loading-animation.gts
stories/5-components/Notifications/AuLoader.stories.js
styles/components/_c-loader.scss
tests/helpers/deprecations.ts
tests/integration/components/au-loader-test.gts
tests/integration/components/loose-mode-test.ts

This updates the `AuLoader` component so it matches the Webuniversum [`<vl-ui-loader>` component](https://overheid.vlaanderen.be/webuniversum/v3/documentation/atoms/vl-ui-loader/).
Notable changes:
- visual loading message by default
- an option to hide the loading message, if needed
- inline loading message variant
- the "old" version is now deprecated
Closes #456 
The existing options that aren't supported by the `<vl-ui-loader>` component are now deprecated.
If you were using the `AuLoader` component without any arguments the component would use a (visually hidden) default message. You can achieve a similar result by passing the previous default message as the block content.
```hbs
{{! Before }}
<AuLoader />
{{! After }}
<AuLoader @hideMessage={{true}}>Aan het laden</AuLoader>
```
Use …

`AuLoader` updates

---

package-lock.json
package.json

The latest stable release of the inputmask library is incompatible with FastBoot. The issue has been fixed, but hasn't been released as a stable release yet. We use the beta as a temporary workaround.
Closes #462

Fix a FastBoot issue caused by inputmask

---

addon/components/au-accordion.gts
addon/components/au-toolbar.gts
addon/template-registry.ts
stories/5-components/Content/AuAccordion.stories.js
tests/integration/components/au-accordion-test.gts
tests/integration/components/au-toolbar-test.gts
tests/integration/components/loose-mode-test.ts

This adds a new ~~`defaultOpen`~~ `isOpenInitially` argument to the `AuAccordion` component which can be used to display the accordion in the open state from the start.
It also adds Glint support to component (also to the `AuToolbar` component, since that's one of its dependencies.)
Closes #461

Add an `isOpenInitially` argument to the `AuAccordion` component

---

addon/components/au-loader.gts
stories/5-components/Notifications/AuLoader.stories.js

The loader is centered by default but this doesn't always look correctly for some use-cases. The `@centered` argument allows you to op-out of the default centering in case you need it.
Closes #472

Add a `@centered` argument to the `AuLoader` component

---

addon/components/au-modal.gjs
addon/private/helpers/class-names.ts
tests/integration/private/helpers/class-names-test.gts

The way the CSS classes where added caused issues due to missing whitespace between the classes. We now use the `{{cn}}` helper which handles that for us. 
Closes #477

Fix incompatibilities between some `AuModal` arguments

---

addon/components/au-accordion.gts
tests/integration/components/au-accordion-test.gts

These tests are frail since they depend on the icon setup and don't really test if it actually works. Ideally we would test this with some kind of visual regression testing setup, but for now we'll just remove the tests.

Remove the icon tests from the `AuAccordion` component

---

addon/components/au-accordion.gts
addon/components/au-alert.gts
addon/components/au-badge.gts
addon/components/au-button.gts
addon/components/au-card.gts
addon/components/au-icon.gts
addon/components/au-input.gts
addon/components/au-link-external.gts
addon/components/au-link.gts
addon/components/au-pill.gts

> [!WARNING]  
> This setup is still in an experimental state. We want to try it out in a couple of specific places before considering this ready to use by all the Appuniversum users. We might still break the setup in future minor versions until we announce it as stable.
<hr>
Another PR in the [line](#424) of [PRs](#430) attempting to address the issue of inline SVGs.
This time the approach is to allow passing of arbitrary components to `AuIcon` (and by extension, any component taking an `@icon` argument).
The advantages of this method are that this is very flexible to the user. Also, by overloading `@icon` it avoids confusion that could be caused by adding a new argument, as only one of `string` or `Component` can be passed.
A minor downside is that the user can potentially pass a …

[Experimental feature] Add support for using components as icons

---

addon/components/au-accordion.gts
addon/components/au-alert.gts
addon/components/au-card.gts
addon/components/au-data-table/number-pagination.hbs
addon/components/au-data-table/number-pagination.js
addon/components/au-data-table/text-search.hbs
addon/components/au-data-table/text-search.js
addon/components/au-data-table/th-sortable.hbs
addon/components/au-data-table/th-sortable.js
addon/components/au-date-input.gts
addon/components/au-dropdown.gjs
addon/components/au-fieldset.gts
addon/components/au-file-card.gts
addon/components/au-file-upload.gts
addon/components/au-label.gts
addon/components/au-main-header.gts
addon/components/au-modal.gjs

This is a good experiment to see if everything works, and it allows projects to skip the svg-symbolset download if they also refactor their own code.
Builds on #483 and is part of #482

Use the icon components internally

---

README.md

Adding this addon to a new Ember app has some prerequisites that are nicely explained in the **Getting started** section of the Storybook, but they're not mentioned/linked to in the README.
This PR adds a link in the README so it's easier to find out how to add the addon.

docs: add link to Getting started in README

---

styles/utilities/_u-flex.scss

The responsive versions of the `.au-u-flex` and `.au-u-flex--wrap` classes weren't being generated yet.

Add missing responsive flex utilities

---

addon/components/au-button.gts
tests/integration/components/au-button-test.gts

The default loading message is a footgun. Many projects forget to properly set this which means the default is used, even though it's not a good fit for the context. This is only made worse by the fact that the AuButton component didn't visually display the loading message originally, so a lot of older code doesn't set this message explicitly.
By requiring an explicit loading message this should no longer be an issue.
Simply add a `@loadingMessage` argument if you are using the `@loading` argument on a `<AuButton>` component. To get the exact same result as the current behavior you can use the following code:
```diff
- <AuButton @loading={{true}}>Some action</AuButton>
+ <AuButton @loading={{true}} @loadingMessage="Aan het laden">Some action</AuButton>
```
There are few places where the …

[AuButton] deprecate the default loading message

---

styles/components/_c-main-header.scss

There are some elements that are also using the alpha z-index, which causes issues if elements inside the main header escape its boundaries (for example dropdowns, or drop shadows). By setting it to the beta value, things should work as expected.
Closes #386

Fix a styling issue in the `AuMainHeader` component

---

styles/components/_c-content.scss

This adds support for ordered lists and tables to the `AuContent` component.
It's not perfect, but I feel the whole au-c-content styling setup needs to be revisited anyways..

Add missing content styles

---

addon/components/au-main-header.gts
stories/5-components/Brand/AuMainHeader.stories.js
stories/5-components/Navigation/AuDropdown.stories.js
styles/components/_c-data-table.scss
styles/components/_c-help-text.scss

Accessibility fixes:
- Fix AuDataTable sortable header color contrast
- Fix secondary helptext color contrast
- Remove aria-controls from aria-live region: not a valid property
Documentation update:
- fix dropdown example: role=menu should not be on the dropdown button
Additions:
- AuMainHeader: add override on the contact link text. Certain products apply a hack to put a different link which breaks the semantics of this component

Accessibility update / Tested for frontend-subsidiepunt

---

.github/workflows/ci.yml
index.js
package-lock.json
package.json
stories/5-components/Content/AuModal.stories.js
stories/5-components/Forms/PowerSelect/MultipleSelect.stories.js
stories/5-components/Forms/PowerSelect/SingleSelect.stories.js
styles/plugins/_p-ember-power-select.scss
tests/dummy/app/templates/application.hbs
tests/dummy/config/ember-try.js

Add support for ember-concurrency v4 and ember-power-select v8

---

styles/plugins/_p-ember-power-select.scss

The active border is now no longer visible when the select is disabled.
Closes #439

Fix a PowerSelect outline issue

---

addon/components/au-badge.gts
addon/components/au-brand.gts
addon/components/au-button.gts
addon/components/au-checkbox.gts
addon/components/au-date-input.gts
addon/components/au-dropdown.gts
addon/components/au-icon.gts
addon/components/au-link-external.gts
addon/components/au-link.gts
addon/components/au-pill.gts
addon/components/au-radio.gts
addon/components/au-textarea.gts
addon/components/au-toggle-switch.gts

Some of our components generate inline(-*) elements which are affected by surrounding whitespace. We used a `{{~!~}}` comment for most of these cases, but it seems comments are stripped in production builds, even if the comment also has whitespace stripping enabled.
As a workaround we now remove the actual whitespace from the source code, even though it makes things harder to read.
Once we convert to a v2 addon we can strip the whitespace at build time and revert this change.
Closes #509

Fix some whitespace issues

---

index.js

A fix for this has now landed in `@embroider/compat`
https://github.com/embroider-build/embroider/blob/stable/CHANGELOG.md#bug-bug-fix-3

Remove our ember-template-tag TS workaround

---

package-lock.json
package.json

The change we needed was released so we no longer need the beta version.

Update to inputmask v5.0.9

---

addon/components/au-link-external.gts
stories/5-components/Links/AuLinkExternal.stories.js
tests/integration/components/au-link-external-test.gts

Add a `@newTab` argument to the `AuLinkExternal` component

---

addon/components/au-button.gts
addon/components/au-link-external.gts
addon/components/au-link.gts
stories/5-components/Buttons/AuButton.stories.js
stories/5-components/Links/AuLink.stories.js
stories/5-components/Links/AuLinkExternal.stories.js
styles/components/_c-button.scss
styles/components/_c-link.scss

https://overheid.vlaanderen.be/webuniversum/v3/documentation/atoms/vl-ui-link
It's needed for the pager component (#527)

Add a "bold" link skin

---

addon/components/au-file-upload.gts

This is very similar to the `@onFinishUpload` action but with a more flexible signature that allows us to easily add new data in the future.
`@onUpload` also receives the `File` instance which allows consumers to display information about the selected file without having to fetch the corresponding data from the database first.
No tests since we don't have a request mocking setup yet and I don't have the time to add one now.

Add a new `@onUpload` action to the `AuFileUpload` component

---

addon/components/au-accordion.gts
addon/components/au-card.gts
addon/private/components/maybe-au-content.gts
ember-cli-build.js

Both the `<AuCard>` and `<AuAccordion>` component use the `<AuContent>` component to add styles to any content the consumer might provide.
This works fine if consumers provide simple html content, but once other components are nested, there are potential styling conflicts.
Instead of embedding the `<AuContent>` consumers should now add the `<AuContent>` component if they need it.
Closes #534
The `<AuCard>` component uses the `<AuContent>` component for its content and footer blocks. If your nest content that depends on the generic styles you need to explicitly add the `<AuContent>` component.
```hbs
{{! Before }}
<AuCard as |card|>
<card.content>
<p>Some html content</p>
</card.content>
<card.footer>
<p>Some html content</p>
</card.footer>
</AuCard>
{{! After }}
<AuCard as |card|> …
```

Deprecate the internal `AuContent` usage
