appuniversum/ember-appuniversum

addon/components/au-link.hbs

Disclaimer: change made with github editor, not tested (I tried, but couldn't figure out how do quickly test it, and there is really no reason this wouldn't work)

Enable usage of the model attribute

---

addon/components/au-time-picker.hbs
addon/components/au-time-picker.js
addon/helpers/format-time.js
app/components/au-time-picker.js
app/helpers/format-time.js
tests/dummy/app/components/sidebar.hbs
tests/dummy/app/router.js
tests/dummy/app/styles/_shame.scss
tests/dummy/app/templates/docs/atoms/au-form-timepicker.md
tests/integration/components/au-time-picker-test.js
tests/integration/helpers/format-time-test.js

Working time picker with keyboard support.
Made some radical changes, biggest being that you can not input numbers yourself. You can do this using keyboard up and down or the plus/minus buttons on the side. Reason being that supporting manual number input is very prone to errors and does not play well with showing double digits (e.g. 04 instead of just 4)
Dont really know if this is going to be problematic for user experience, as a compensation I can add support for incrementing/decrementing time value while one of the buttons is being held down.
Let me know what you think :)
btw the PR request in pointed towards development branch instead of master

Dev/time picker (will need a review first see description)

---

addon/components/au-date-picker.hbs
addon/components/au-date-picker.js
addon/components/au-time-picker.hbs
addon/components/au-time-picker.js
tests/dummy/app/templates/docs/atoms/au-form-datepicker-demo/on-change.js
tests/dummy/app/templates/docs/atoms/au-form-datepicker.md
tests/dummy/app/templates/docs/atoms/au-form-timepicker.md

**Time-picker**
- You can set values through attributes
- onChange attribute has been added that returns an object with all time values when a change is made
- tested seperatly
- updated docs with changes
**Date-picker**
- onChange attribute has been added that returns the element object including date value when a change is made
- tested seperatly
- updated docs with changes

Add time-picker & date-picker functionality

---

app/helpers/format-time.js

The named export does not exist.

Remove the named reexport for the formatTime helper

---

addon/components/au-control-radio.hbs
addon/components/au-control-radio.js

allow an onchange action to be set on a radio button

---

addon/components/au-input.hbs
addon/components/au-input.js
addon/components/au-textarea.hbs
addon/components/au-textarea.js
app/styles/ember-appuniversum/_c-input.scss
app/styles/ember-appuniversum/_c-textarea.scss
tests/dummy/app/templates/docs/atoms/au-form-input.md
tests/dummy/app/templates/docs/atoms/au-form-textarea.md

See #131
Changes:
- adds @disabled argument
- makes disabled state consistent with other fields

Fix disabled state on input and textarea

---

addon/components/au-card.js
package-lock.json
package.json
tests/dummy/app/templates/docs/components/au-card.md

there's room for improvement here, but it works for the basic case.

allow users to specify whether au-card is open on init or not

---

addon/components/au-table.hbs
addon/components/au-table.js
app/components/au-table.js
app/styles/ember-appuniversum.scss
app/styles/ember-appuniversum/_c-table.scss
package-lock.json
package.json
tests/dummy/app/components/sidebar.hbs
tests/dummy/app/router.js
tests/dummy/app/templates/docs/components/au-table.md
tests/dummy/app/templates/docs/outline/webuniversum.md
tests/integration/components/au-table-test.js

Simple table component.
@Windvis Can you review the use of the named blocks? Not sure if I use this correctly or if we can/should also make components out of the tr, th, td elements.

Table component

---

addon/components/au-link.hbs
addon/components/au-link.js

use a getter as a workaround to provide query params to LinkTo

---

tests/dummy/app/templates/docs/atoms/au-form-datepicker.md

I forgot to update the snippet name in the last PR :grimacing:

Show the correct code snippet for the AuDatepicker error state

---

addon/components/au-modal.hbs
addon/components/au-modal.js
app/styles/ember-appuniversum/_c-modal.scss
app/styles/ember-appuniversum/_c-pagination.scss
app/styles/ember-appuniversum/_c-table.scss
package-lock.json
tests/dummy/app/components/sidebar.hbs
tests/dummy/app/router.js
tests/dummy/app/templates/docs/components/au-modal.md
tests/dummy/app/templates/docs/components/au-pagination.md

- add padding option to modal
- make pagination full width
- add pagination page
- add additional components to table

Changes for roadsign regulation plugin

---

addon/components/au-date-picker.hbs
addon/components/au-date-picker.js
addon/components/au-help-text.hbs
addon/components/au-help-text.js
addon/components/au-input.hbs
addon/components/au-input.js
addon/components/au-label.hbs
addon/components/au-label.js
addon/components/au-textarea.hbs
addon/components/au-textarea.js
app/styles/ember-appuniversum/_c-help-text.scss
app/styles/ember-appuniversum/_c-input.scss
app/styles/ember-appuniversum/_c-label.scss
app/styles/ember-appuniversum/_c-textarea.scss
app/styles/ember-appuniversum/_p-duet-datepicker.scss
tests/dummy/app/templates/docs/atoms/au-form-datepicker.md
tests/dummy/app/templates/docs/atoms/au-form-input.md
tests/dummy/app/templates/docs/atoms/au-form-label.md
tests/dummy/app/templates/docs/atoms/au-form-textarea.md
tests/dummy/app/templates/docs/atoms/au-helptext.md

See #163
Also refactored the way icons are shown before labels. Replaced the before element with a badge component.

Add warning states to inputs, labels and helptext

---

.github/workflows/ci.yml
app/components/card-edit.js
tests/dummy/app/index.html

Enable the Embroider scenarios again in CI

---

app/styles/ember-appuniversum.scss
app/styles/ember-appuniversum/_a-components.scss
app/styles/ember-appuniversum/_a-elements.scss
app/styles/ember-appuniversum/_a-generic.scss
app/styles/ember-appuniversum/_a-objects.scss
app/styles/ember-appuniversum/_a-plugins.scss
app/styles/ember-appuniversum/_a-settings.scss
app/styles/ember-appuniversum/_a-tools.scss
app/styles/ember-appuniversum/_a-utilities.scss
stories/1-outline/Getting-started.stories.mdx

Group scss imports

---

addon/components/au-input.hbs
app/styles/ember-appuniversum/_c-input.scss

Make input-wrapper adapt to the width of the input

---

package-lock.json
package.json
stories/3-utilities/Typography.stories.mdx

- upgrade appuniversum to 1.0.0
- add color utility docs to typography section

Add color utilities

---

addon/components/au-file-card.hbs
addon/components/au-file-card.js
app/components/au-file-card.js
app/styles/ember-appuniversum/_a-components.scss
app/styles/ember-appuniversum/_c-file-card.scss
stories/4-components/Content/AuFileCard.stories.js
tests/integration/components/au-file-card-test.js

Based on the [custom vo-mu-filecard component in Loket](https://github.com/lblod/frontend-loket/blob/2a514e74f9b509a472bdc6033a37505fd0fde93f/app/templates/components/vo-mu-file-card.hbs).
Closes #213

Add a `AuFileCard` component

---

addon/components/au-accordion.hbs
addon/components/au-accordion.js
app/styles/ember-appuniversum/_c-accordion.scss
app/styles/ember-appuniversum/_c-button.scss
stories/4-components/Content/AuAccordion.stories.js

- reverse option
- border skin option

Extend accordion layout options

---

addon/components/au-data-table/content-body.hbs
addon/components/au-data-table/content-header.hbs
addon/components/au-data-table/default-data-table-content-body.hbs
addon/components/au-data-table/number-pagination.hbs
stories/4-components/Tables/AuDataTable.stories.js

Combined with https://github.com/mu-semtech/ember-data-table/pull/32 I couldn't find any deprecation warnings (caused by the data-table components) anymore.

Fix remaining deprecations triggered by ember-data-table

---

addon/components/au-list.hbs
addon/components/au-list.js
addon/components/au-list/item.hbs
app/components/au-list.js
app/components/au-list/item.js
app/styles/ember-appuniversum/_a-components.scss
app/styles/ember-appuniversum/_c-accordion.scss
app/styles/ember-appuniversum/_c-list.scss
stories/4-components/Content/AuList.stories.js

Added:
- list component
- accordion fixes

List component and accordion fix

---

app/styles/ember-appuniversum/_p-ember-power-select.scss

Fix power select padding and line height

---

addon/components/au-button.hbs
addon/components/au-button.js
addon/components/au-link.js
app/styles/ember-appuniversum/_c-button.scss
stories/4-components/Buttons/AuButton.stories.js
stories/4-components/Links/AuLink.stories.js
stories/4-components/Links/AuLinkExternal.stories.js

Changed the design to follow the webuniversum spec:
- added naked skin
- changed disabled and loading state
I ommited the tertiary button option as I don't see an immediate use for it. 3 button variants should offer enough hiërarchy.

Update the `AuButton` component so it matches the latest Webuniversum version

---

addon/components/au-link.hbs
addon/components/au-tabs.hbs
addon/components/au-tabs/item.hbs
app/components/au-tabs.js
app/components/au-tabs/item.js
app/styles/ember-appuniversum/_a-components.scss
app/styles/ember-appuniversum/_c-link.scss
app/styles/ember-appuniversum/_c-tabs.scss
stories/1-outline/Getting-started.stories.mdx
stories/4-components/Navigation/AuTabs.stories.js
tests/integration/components/au-tabs-test.js
tests/integration/components/au-tabs/item-test.js

Adds a tab component according to the webuniversum design:

Tabs component

---

addon/components/au-list.hbs
addon/components/au-list/item.js
addon/components/au-tabs.hbs
stories/4-components/Content/AuList.stories.js
stories/4-components/Navigation/AuTabs.stories.js

Fix for https://github.com/appuniversum/ember-appuniversum/pull/261#discussion_r875919373
Also fixed the list component. Not sure if I should add the deprecate here as it's a fairly new component and only used in a few places so far.

Yield tabs item and list item

---

addon/components/au-pill.hbs
addon/components/au-pill.js
stories/4-components/Notifications/AuPill.stories.js
tests/integration/components/au-pill-test.js

Fix for (broken) pill component action.
@Dietr I presume that, due to the error/bug being present, it (pill with an action) is not being used in any project at the moment? So changing argument names won't have any effect? 🤞

Rework pill component action

---

addon/components/au-modal.hbs
addon/components/au-modal.js

Fix for #273 
See also https://github.com/lblod/frontend-organization-portal/commit/f3c09d80e7afc548cb28e69c8c89fa18b187ab49
@Windvis Not sure if this is undoing your previous modal fix? Can you have a look?

Apply modal fix

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/workflows/chromatic.yml
CONTRIBUTING.md
README.md

Proposal to create/document a more consistent issue and new feature flow:
- updated contributing page with new feature flow
- issue templates to promote better bug reports and feature requests

Update issue templates

---

.storybook/preview.js
app/styles/ember-appuniversum/_c-accordion.scss
app/styles/ember-appuniversum/_c-dropdown.scss
app/styles/ember-appuniversum/_c-list-navigation.scss
app/styles/ember-appuniversum/_c-list.scss
app/styles/ember-appuniversum/_c-main-footer.scss
app/styles/ember-appuniversum/_c-pagination.scss
app/styles/ember-appuniversum/_c-sidebar-action.scss
app/styles/ember-appuniversum/_c-table.scss
app/styles/ember-appuniversum/_c-tabs.scss
app/styles/ember-appuniversum/_c-toolbar.scss
app/styles/ember-appuniversum/_p-ember-power-select.scss
package-lock.json
package.json
stories/2-variables/Colors.stories.mdx
stories/2-variables/CssVariables.stories.mdx
stories/2-variables/SassVariables.stories.mdx
stories/2-variables/Semantic-colors.stories.mdx

Fixes #285:
- Update appuniversum
- Use global divider variable

Use global divider variable

---

package-lock.json
package.json

This resolves a Ember 4 deprecation warning in the tests.

Update ember-data-table to v2.1.0

---

.github/workflows/ci.yml
README.md
config/ember-try.js

Remove support for Ember 3.20 and 3.24 

---

addon/components/au-main-container/sidebar.hbs
addon/components/au-main-container/sidebar.js
app/styles/ember-appuniversum/_c-app.scss
app/styles/ember-appuniversum/_c-body-container.scss
app/styles/ember-appuniversum/_c-main-container.scss
stories/5-components/Layout/AuApp.stories.js
stories/5-components/Layout/AuMainContainer.stories.js

- Make app and main container more robust (autosizing when multiple headers are present): fixes #309
- Expand use of sidebar (multiple sizes, multiple sidebars)

Fix App container bug and improve sidebar

---

stories/6-patterns/buttons.stories.js

Document button placement and best practices

---

addon/components/au-panel.hbs
addon/components/au-panel/section.hbs
app/components/au-panel.js
app/components/au-panel/section.js
app/styles/ember-appuniversum/_a-components.scss
app/styles/ember-appuniversum/_c-panel.scss
stories/5-components/Content/AuPanel.stories.js
tests/integration/components/au-panel-test.js
tests/integration/components/au-panel/section-test.js

Component for the Kaleidos UI but could allow us to simplify the AuCard component (which is quite complex) in the future as it solves some of its use cases.

Panel component

---

addon/components/au-dropdown.hbs
addon/components/au-dropdown.js
app/styles/ember-appuniversum/_c-button.scss
app/styles/ember-appuniversum/_c-dropdown.scss
app/styles/ember-appuniversum/_c-main-header.scss
stories/5-components/Brand/AuMainHeader.stories.js
stories/5-components/Navigation/AuDropdown.stories.js
stories/7-templates/AppBreadcrumbs.stories.js
stories/7-templates/AppEditor.stories.js
stories/7-templates/AppSidebar.stories.js
tests/integration/components/au-dropdown-test.js

- use AuButton component
- allow <AuHr /> component as a divider element
- simplify component

Rework dropdown

---

addon/components/au-button.hbs
app/styles/ember-appuniversum/_c-button.scss
stories/5-components/Buttons/AuButton.stories.js

Added for https://github.com/lblod/ember-rdfa-editor-table-of-contents-plugin/pull/12

Add wrap property to a button

---

app/styles/ember-appuniversum/_c-button.scss

Fix focus state on loading buttons

---

addon/components/au-dropdown.js
stories/5-components/Navigation/AuDropdown.stories.js
tests/integration/components/au-dropdown-test.js

Add an `@onClose` argument to the `AuDropdown` component 

---

addon/components/au-alert.js
stories/5-components/Notifications/AuAlert.stories.js
tests/integration/components/au-alert-test.js

Add an `@onClose` argument to the `AuAlert` component

---

addon/components/au-accordion.hbs
addon/components/au-content-header.hbs

- fix landmark for content header
- simplify accordion component

Additional accessibility errors

---

addon/services/toaster.js
stories/5-components/Notifications/Toasts/Documentation.stories.mdx
stories/5-components/Notifications/Toasts/Examples.stories.js
tests/dummy/app/components/au-toast-demo.hbs
tests/dummy/app/components/au-toast-demo.js

- rename the method to `close` which seems like a better fit
- add some documentation
- rework the existing documentation

Some toaster tweaks

---

addon/services/toaster.js
stories/5-components/Notifications/Toasts/Documentation.stories.mdx
stories/5-components/Notifications/Toasts/Examples.stories.js
tests/dummy/app/components/au-toast-demo.hbs
tests/dummy/app/components/au-toast-demo.js

The addition of a clear function within the `toaster` service.
More information can be found inside the complementary FR: https://github.com/appuniversum/ember-appuniversum/issues/413.

Addition of clear action within toaster service

---

README.md
package.json

Drop support for node 14 and 16

---

package-lock.json
package.json

This bumps dependencies to the newest major versions supported by our support range.

Update dependencies to newest majors matching our support range

---

stories/1-outline/Getting-started.stories.mdx
stories/4-utilities/Heights.stories.mdx
styles/_a-utilities.scss
styles/utilities/_u-heights.scss

This is common enough to warrant a new utility.
Closes #510

Add a `au-u-height-full` utility

---

addon/components/au-data-table.hbs
addon/components/au-data-table.js
stories/5-components/Tables/AuDataTable.stories.js
tests/integration/components/au-data-table-test.gjs

Add support for hiding the pagination in the `AuDataTable` component

---

stories/5-components/Notifications/AuPill.stories.js

An exception was being thrown which broke the Story.
Closes #536

Fix the `<AuPill>` story

---

public/icons/paragraph.svg
stories/assets/icons.js
tests/dummy/app/components/au-icon-list.js

Add paragraph icon that we need for the editor present in webuniversum

add paragraph icon
